# appVersionOverride:

init:
  image:
    registry: docker.io
    repository: alpine
    tag: 3.23
    pullPolicy: IfNotPresent

image:
  registry: ghcr.io
  repository: codecentric/habitcentric/habit
  tag: latest
  ## Specifies an imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: Always

## Configure extra environment variables for the container
extraEnv: []

## habitcentric habit service configuration
service:
  ## Additional service annotations which may be required
  annotations: {}

  ## ServiceType
  ## ref: https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types
  type: ClusterIP

  ## Internal service port
  port: 9001

  ## nodePort value for the LoadBalancer and NodePort service types
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  # nodePort:

persistence:
  deployPostgres: true
  ## Enable init container to wait for postgresql availability
  enableInitContainer: true
  ## Name of custom database (if deployPostgres=false)
  # dbName:

  ## Host of custom database (if deployPostgres=false)
  # dbHost:

  ## Port of custom database (if deployPostgres=false)
  # dbPort:

  ## User of custom database (if deployPostgres=false)
  # dbUser:

  ## Password of custom database (if deployPostgres=false)
  # dbPassword:

## Pod Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  enabled: false

  ## Name of an already existing service account. Setting this value disables the automatic service account creation.
  # name:

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Number of service instances
replicas: 1

## Additional pod labels which may be required
podLabels: {}

## Additional pod annotations which may be required
podAnnotations: {}

## updateStrategyType for habitcentric habit Deployment
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
updateStrategyType: RollingUpdate

postgresql:
  nameOverride: habit-postgresql

  ## Default port for the habit-postgresql
  primary:
    service:
      ports:
        postgresql: 10001

  auth:
    username: habit
    password: habit
    database: habit
    postgresPassword: postgres
