name: auth keycloak

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/auth-keycloak.yaml
      - services/auth-keycloak

jobs:
  build:
    name: ğŸ”¨ Build service
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2
      - name: ğŸ§° Build container image
        working-directory: services/auth-keycloak
        run: |
          docker build \
            -t "ghcr.io/codecentric/habitcentric/auth-keycloak:latest" \
            -t "ghcr.io/codecentric/habitcentric/auth-keycloak:$(git rev-parse --short HEAD)" .
      - name: ğŸ”‘ Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: â¬†ï¸ Push container image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push "ghcr.io/codecentric/habitcentric/auth-keycloak:latest"
          docker push "ghcr.io/codecentric/habitcentric/auth-keycloak:$(git rev-parse --short HEAD)"
